export global Palette {
    // Dark mode
    in-out property <bool> dark-mode: false;

    // ---- Colors ------------------------------------------------------------
    out property <color> white: #FFFFFF;
    out property <color> neutral_50: #FAFAFA;
    out property <color> neutral_100: #F5F5F5;
    out property <color> neutral_200: #E5E5E5;
    out property <color> neutral_300: #D4D4D4;
    out property <color> neutral_400: #A3A3A3;
    out property <color> neutral_500: #737373;
    out property <color> neutral_600: #525252;
    out property <color> neutral_700: #404040;
    out property <color> neutral_800: #262626;
    out property <color> neutral_900: #171717;
    out property <color> neutral_950: #0A0A0A;
    out property <color> black: #000000;

    out property <color> accent-light: #557A95;
    out property <color> accent-dark: #74A7CC;

    out property <color> amber_400: #FBBF24;
    out property <color> lime_500: #22C55E;
    out property <color> red_500: #EF4444;

    // ---- Base Palette ------------------------------------------------------
    out property <brush> background: dark-mode ? neutral_800 : neutral_100;
    out property <brush> foreground: dark-mode ? neutral_50 : neutral_800;
    // out property <brush> alternate-background: dark-color-scheme ? #2c2c2c : #00000005;
    // out property <brush> alternate-foreground: dark-color-scheme ? #ffffff : #000000;
    // out property <brush> control-background: dark-color-scheme ? #616161 : #ffffff;
    // out property <brush> control-foreground: dark-color-scheme ? #ffffff : #000000;
    // out property <brush> accent-background: dark-color-scheme ? #0055d1 : #007AFF;
    // out property <brush> accent-foreground: #f0f0f0;
    // out property <brush> selection-background: dark-color-scheme ? #0055d14D : #007AFF4D;
    // out property <brush> selection-foreground: dark-color-scheme ? #ffffff : #000000;
    // out property <brush> border: dark-color-scheme ? #ffffff26 : #00000026;

    out property <color> accent: dark-mode ? accent-dark : accent-light;

    // ---- Animation ---------------------------------------------------------
    out property <duration> default_duration: 50ms;

    // ---- Sizes -------------------------------------------------------------
    out property <{height: length, width: length}> min_size: { height: 20px, width: 20px };
}
