import { Button, ButtonTest } from "gossip/button.slint";
import { Palette as gp } from "gossip/style.slint";

export component AppWindow inherits Window {
    // looks
    background: gp.background;
    default-font-family: "DejaVu Sans";
    default-font-weight: 300;

    VerticalLayout {
        padding: 20px;
        spacing: 20px;
        vertical-stretch: 0;
        horizontal-stretch: 0;

        Button {
            type: bordered;
            text: {
                if gp.dark-mode {
                    "to light-mode"
                } else {
                    "to dark-mode"
                }
            };
            clicked => {
                if gp.dark-mode {
                    gp.dark-mode = false;
                } else {
                    gp.dark-mode = true;
                }
            }
        }

        ButtonTest { }
    }
}
